### ISSUE TITLE
Instalar módulo de TodoPago

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-ho#1]
Al intentar instalar el módulo de todo pago, se obtuvo el siguiente mensaje de error.
![image](https://user-images.githubusercontent.com/27778036/124370833-c590e080-dc51-11eb-8e45-20dbeec75946.png)

**Comment by jobiols** [comment]
@sebatista se instaló la dependencia faltante

**Comment by jobiols** [comment]
@sebatista se instaló la dependencia faltante
